export default interface ActionType {
  address: string;
  address_link: string;
  admin_created: number;
  admin_modified: number;
  categories: string[];
  client_id: number;
  comment_count: number;
  comments: []
  condition: string;
  coupon_max: number;
  coupon_min: number;
  coupon_price: number;
  coupon_sold: number;
  css: string;
  date_created: number;
  date_end: number;
  date_modified: number;
  date_start: number;
  description: string;
  discount: number;
  id: number;
  image: string;
  image_big: string;
  left: number;
  map: null
  name: string;
  phone: string;
  price: number;
  published: number;
  salary_date_end: number;
  salary_date_start: number;
  schedule: string;
  short: string;
  site: string;
  subscribe: 0
  timetable: any;
  type: number;
  url: string;
  url_name: string;
  user_id: null;
}